name: gdpr-obfuscation-deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    # implement make file execution
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      #Set up python
      - name: use-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"
      - name: Run all checks
        run: make all

  deploy-lambda:
    name: deploy-lambda
    runs-on: ubuntu-latest
    needs: run-tests
    environment: dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        #Install terraform
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Setup AWS cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.sec_reg }}
          aws-access-key-id: ${{ secrets.sec_key }} 
          aws-secret-access-key: ${{ secrets.sec_access }}
      
      - name: Build Lambda zip
        run:
          mkdir -p packages
          zip -r packages/lambda_package.zip src/*
      # terraform init
      - name: Terraform init 
        working-directory: terraform
        run: terraform init
      
      
      # terraform plan
      - name: Terraform plan 
        working-directory: terraform
        run: terraform plan 
      # terraform fmt
      - name: Terraform format
        working-directory: terraform
        run: terraform fmt
      # terraform apply
      - name: Terraform apply
        working-directory: terraform 
        run: terraform apply -auto-approve